FROM alpine:latest

# Install git, curl, GitHub CLI, and Bash
RUN apk add --no-cache git curl github-cli bash jq coreutils

# Copy your scripts and issues directory
COPY startup.sh /startup.sh 
COPY shutdown.sh /shutdown.sh
COPY test.sh /test.sh
COPY master.sh /master.sh
COPY /issues /issues

# Make your scripts executable
RUN chmod +x /startup.sh /test.sh /shutdown.sh /master.sh
ENTRYPOINT ["/master.sh"]